hibernate.dialect= org.hibernate.dialect.Oracle9Dialect hibernate.connection.driver_class= oracle.jdbc.driver.OracleDriver
hibernate.connection.url= jdbc:postgresql:@localhost:5432:postgres hibernate.connection.username=user hibernate.connection.password=password
hibernate.show_sql=true hibernate.hbm2ddl=update

SessionFactory=sessionFactory = new Configuration().buildSessionFactory();

